[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gemini/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
